//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bifler {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bifler.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude.
        /// </summary>
        internal static string Altitude {
            get {
                return ResourceManager.GetString("Altitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال حاضر شما یک نسخه دیگر از برنامه را باز گذاشته اید.
        /// </summary>
        internal static string AppIsAlreadyOpen {
            get {
                return ResourceManager.GetString("AppIsAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کالیبر.
        /// </summary>
        internal static string Caliber {
            get {
                return ResourceManager.GetString("Caliber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پایان کالیبریشن.
        /// </summary>
        internal static string CaliberFinish {
            get {
                return ResourceManager.GetString("CaliberFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروع کالیبریشن.
        /// </summary>
        internal static string CaliberStart {
            get {
                return ResourceManager.GetString("CaliberStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوربین.
        /// </summary>
        internal static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوربین در برنامه دیگری (و یا تنظیمات باسلر) باز است، لطفا برنامه دیگر را بسته و برنامه برداشت را دوباره باز کنید..
        /// </summary>
        internal static string CameraAlreadyOpen {
            get {
                return ResourceManager.GetString("CameraAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخصات دوربین.
        /// </summary>
        internal static string CameraInformation {
            get {
                return ResourceManager.GetString("CameraInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تصویر دوربین.
        /// </summary>
        internal static string CameraPhotoIndex {
            get {
                return ResourceManager.GetString("CameraPhotoIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصویر دوربین.
        /// </summary>
        internal static string CameraPicture {
            get {
                return ResourceManager.GetString("CameraPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام شهرستان.
        /// </summary>
        internal static string CityName {
            get {
                return ResourceManager.GetString("CityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قطع اتصال با دوربین زیر:.
        /// </summary>
        internal static string DeviceDisconnected {
            get {
                return ResourceManager.GetString("DeviceDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا مطمعنید مایل به اتمام پروژه هستید؟.
        /// </summary>
        internal static string EndProjectRequest {
            get {
                return ResourceManager.GetString("EndProjectRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پایان پروژه.
        /// </summary>
        internal static string EndProjectText {
            get {
                return ResourceManager.GetString("EndProjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوربین مورد نظر در پیکربندی موجود نیست..
        /// </summary>
        internal static string ErrorExposure {
            get {
                return ResourceManager.GetString("ErrorExposure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای اصلی، لطفا فایل زیر را به پشتیبان ارسال کنید..
        /// </summary>
        internal static string ErrorLogFile {
            get {
                return ResourceManager.GetString("ErrorLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محور پایان.
        /// </summary>
        internal static string FinishArea {
            get {
                return ResourceManager.GetString("FinishArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پایان یافته.
        /// </summary>
        internal static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان پایان.
        /// </summary>
        internal static string FinishTime {
            get {
                return ResourceManager.GetString("FinishTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای ایجاد فایل های پروژه، لطفا پوشه پروژه را چک کنید..
        /// </summary>
        internal static string FolderError {
            get {
                return ResourceManager.GetString("FolderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کامل.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهت جغرافیایی.
        /// </summary>
        internal static string GeoDirection {
            get {
                return ResourceManager.GetString("GeoDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoHeight.
        /// </summary>
        internal static string GeoHeight {
            get {
                return ResourceManager.GetString("GeoHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در اتصال دستگاه موقعیت یاب در درگاه خواسته شده.
        ///لطفا درگاه دیگری را امتحان کنید..
        /// </summary>
        internal static string GPSConnectionFailure {
            get {
                return ResourceManager.GetString("GPSConnectionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دستگاه موقعیت یاب متصل است..
        /// </summary>
        internal static string GPSConnectionSuccess {
            get {
                return ResourceManager.GetString("GPSConnectionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        internal static string GPSIndex {
            get {
                return ResourceManager.GetString("GPSIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متراژ برداشت.
        /// </summary>
        internal static string GrabCount {
            get {
                return ResourceManager.GetString("GrabCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اندیس.
        /// </summary>
        internal static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال بارگذاری مرکز برنامه.
        /// </summary>
        internal static string InitializingCore {
            get {
                return ResourceManager.GetString("InitializingCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال بارگذاری دستگاه موقعیت یاب.
        /// </summary>
        internal static string InitializingGPS {
            get {
                return ResourceManager.GetString("InitializingGPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کیلومتر.
        /// </summary>
        internal static string Kilometer {
            get {
                return ResourceManager.GetString("Kilometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لاین.
        /// </summary>
        internal static string Lane {
            get {
                return ResourceManager.GetString("Lane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد خطوط.
        /// </summary>
        internal static string LaneCount {
            get {
                return ResourceManager.GetString("LaneCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lat.
        /// </summary>
        internal static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال اجرای برنامه.
        /// </summary>
        internal static string LoadingFinished {
            get {
                return ResourceManager.GetString("LoadingFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lon.
        /// </summary>
        internal static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توجه: برای استفاده از مپ اکیدا توصیه میشود خودرو در حالت توقف کامل باشد. در صورتی که خودروی شما در حالت توقف کامل قرار دارد، گزینه اوکی را بزنید.
        /// </summary>
        internal static string MapWarning {
            get {
                return ResourceManager.GetString("MapWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متر.
        /// </summary>
        internal static string Meter {
            get {
                return ResourceManager.GetString("Meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خیر.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروع نشده.
        /// </summary>
        internal static string NotStarted {
            get {
                return ResourceManager.GetString("NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا کمی صبر کنید....
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ها.
        /// </summary>
        internal static string PluralS {
            get {
                return ResourceManager.GetString("PluralS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال اجرا.
        /// </summary>
        internal static string Progressing {
            get {
                return ResourceManager.GetString("Progressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد پروژه.
        /// </summary>
        internal static string ProjectCode {
            get {
                return ResourceManager.GetString("ProjectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان پایان پروژه.
        /// </summary>
        internal static string ProjectFinishTime {
            get {
                return ResourceManager.GetString("ProjectFinishTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخصات پروژه.
        /// </summary>
        internal static string ProjectInformation {
            get {
                return ResourceManager.GetString("ProjectInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام پروژه.
        /// </summary>
        internal static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آماده اجرا.
        /// </summary>
        internal static string ProjectPending {
            get {
                return ResourceManager.GetString("ProjectPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان شروع پروژه.
        /// </summary>
        internal static string ProjectStartTime {
            get {
                return ResourceManager.GetString("ProjectStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت پروژه.
        /// </summary>
        internal static string ProjectStatus {
            get {
                return ResourceManager.GetString("ProjectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان پروژه.
        /// </summary>
        internal static string ProjectTime {
            get {
                return ResourceManager.GetString("ProjectTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد استان.
        /// </summary>
        internal static string ProvinceCode {
            get {
                return ResourceManager.GetString("ProvinceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام استان.
        /// </summary>
        internal static string ProvinceName {
            get {
                return ResourceManager.GetString("ProvinceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا، درایور های دوربین به درستی نصب نیستند..
        /// </summary>
        internal static string PylonLibraryError {
            get {
                return ResourceManager.GetString("PylonLibraryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال بارگذاری درایور های دوربین.
        /// </summary>
        internal static string PylonLibraryLoading {
            get {
                return ResourceManager.GetString("PylonLibraryLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازه.
        /// </summary>
        internal static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اندیس برنامه.
        /// </summary>
        internal static string SaveIndex {
            get {
                return ResourceManager.GetString("SaveIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در اتصال دستگاه موقعیت یاب. لطفا کابل مورد نظر را چک کنید و یا آن را جا به جا کنید..
        /// </summary>
        internal static string SerialConnectionError {
            get {
                return ResourceManager.GetString("SerialConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محور شروع.
        /// </summary>
        internal static string StartArea {
            get {
                return ResourceManager.GetString("StartArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کیلومتر شروع.
        /// </summary>
        internal static string StartKilometer {
            get {
                return ResourceManager.GetString("StartKilometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان شروع.
        /// </summary>
        internal static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کیلومتراژ.
        /// </summary>
        internal static string TraveledUnit {
            get {
                return ResourceManager.GetString("TraveledUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال بارگذاری دستگاه تریگر.
        /// </summary>
        internal static string TriggerConnecting {
            get {
                return ResourceManager.GetString("TriggerConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در اتصال دستگاه تریگر. لطفا کابل مورد نظر را چک کنید و یا آن را جا به جا کنید..
        /// </summary>
        internal static string TriggerConnectionError {
            get {
                return ResourceManager.GetString("TriggerConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در اتصال دستگاه تریگر در پورت خواسته شده.
        ///لطفا پورت دیگری را امتحان کنید..
        /// </summary>
        internal static string TriggerConnectionFailure {
            get {
                return ResourceManager.GetString("TriggerConnectionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دستگاه تریگر متصل است..
        /// </summary>
        internal static string TriggerConnectionSuccess {
            get {
                return ResourceManager.GetString("TriggerConnectionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد تریگر.
        /// </summary>
        internal static string TriggerCount {
            get {
                return ResourceManager.GetString("TriggerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to احتیاط.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
